name: check-out-and-pull-repo
on:
  push:
    branches:
      - master
jobs:
  checkout-and-display-files-job:
    runs-on: unbuntu-latest
    steps:
      - name: list before checkout
        run: ls -la
      - name: checkout
        run: |
          git init
           git remote add origin "https:://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
           git fetch origin
           git checkout master
      - name: list after checkout
        run: ls -la
