name: first workflow
on:
  push:
    branches:
      - master
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: run-shell-command-step
        run: echo "hello world"
      - name: echo step
        run: |
          echo "This is my first CI/CD pipeline"
          echo "Hello ${{ github.event_name }}
