name: first-ci-cd
on:
  push:
    branches: ['master']
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world"
      - name: run multi-line-command
        run: |
          node -v
          echo "npm version" npm -v
