name: first-ci-cd
on:
  push:
    branches: ['master']
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world"
      - name: run multi-line-command
        run: |
          node -v
          echo "npm version" 
          npm -v
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: software version
        run: |
          sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: [run-shell-command, parallel-job]
    steps:
      - name: dependent job step
        run: echo "this is a dependant job"
